/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CalendarPeriodDTO', 'model/InstallationDTO', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CalendarPeriodDTO'), require('./InstallationDTO'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.CalendarDTO = factory(root.MomitApi.ApiClient, root.MomitApi.CalendarPeriodDTO, root.MomitApi.InstallationDTO, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, CalendarPeriodDTO, InstallationDTO, RestLink) {
  'use strict';




  /**
   * The CalendarDTO model module.
   * @module model/CalendarDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>CalendarDTO</code>.
   * @alias module:model/CalendarDTO
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>CalendarDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CalendarDTO} obj Optional instance to populate.
   * @return {module:model/CalendarDTO} The populated <code>CalendarDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('installationId')) {
        obj['installationId'] = InstallationDTO.constructFromObject(data['installationId']);
      }
      if (data.hasOwnProperty('friendlyName')) {
        obj['friendlyName'] = ApiClient.convertToType(data['friendlyName'], 'String');
      }
      if (data.hasOwnProperty('periods')) {
        obj['periods'] = ApiClient.convertToType(data['periods'], [CalendarPeriodDTO]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/InstallationDTO} installationId
   */
  exports.prototype['installationId'] = undefined;
  /**
   * @member {String} friendlyName
   */
  exports.prototype['friendlyName'] = undefined;
  /**
   * @member {Array.<module:model/CalendarPeriodDTO>} periods
   */
  exports.prototype['periods'] = undefined;



  return exports;
}));


