/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.CalendarPeriodDTO = factory(root.MomitApi.ApiClient, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, RestLink) {
  'use strict';




  /**
   * The CalendarPeriodDTO model module.
   * @module model/CalendarPeriodDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>CalendarPeriodDTO</code>.
   * @alias module:model/CalendarPeriodDTO
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>CalendarPeriodDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CalendarPeriodDTO} obj Optional instance to populate.
   * @return {module:model/CalendarPeriodDTO} The populated <code>CalendarPeriodDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('weekDayActive')) {
        obj['weekDayActive'] = ApiClient.convertToType(data['weekDayActive'], 'Number');
      }
      if (data.hasOwnProperty('setPoint')) {
        obj['setPoint'] = ApiClient.convertToType(data['setPoint'], 'Number');
      }
      if (data.hasOwnProperty('startHour')) {
        obj['startHour'] = ApiClient.convertToType(data['startHour'], 'Number');
      }
      if (data.hasOwnProperty('startMinute')) {
        obj['startMinute'] = ApiClient.convertToType(data['startMinute'], 'Number');
      }
      if (data.hasOwnProperty('stopHour')) {
        obj['stopHour'] = ApiClient.convertToType(data['stopHour'], 'Number');
      }
      if (data.hasOwnProperty('stopMinute')) {
        obj['stopMinute'] = ApiClient.convertToType(data['stopMinute'], 'Number');
      }
      if (data.hasOwnProperty('onMonday')) {
        obj['onMonday'] = ApiClient.convertToType(data['onMonday'], 'Boolean');
      }
      if (data.hasOwnProperty('onTuesday')) {
        obj['onTuesday'] = ApiClient.convertToType(data['onTuesday'], 'Boolean');
      }
      if (data.hasOwnProperty('onWednesday')) {
        obj['onWednesday'] = ApiClient.convertToType(data['onWednesday'], 'Boolean');
      }
      if (data.hasOwnProperty('onThursday')) {
        obj['onThursday'] = ApiClient.convertToType(data['onThursday'], 'Boolean');
      }
      if (data.hasOwnProperty('onFriday')) {
        obj['onFriday'] = ApiClient.convertToType(data['onFriday'], 'Boolean');
      }
      if (data.hasOwnProperty('onSaturday')) {
        obj['onSaturday'] = ApiClient.convertToType(data['onSaturday'], 'Boolean');
      }
      if (data.hasOwnProperty('onSunday')) {
        obj['onSunday'] = ApiClient.convertToType(data['onSunday'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} weekDayActive
   */
  exports.prototype['weekDayActive'] = undefined;
  /**
   * @member {Number} setPoint
   */
  exports.prototype['setPoint'] = undefined;
  /**
   * @member {Number} startHour
   */
  exports.prototype['startHour'] = undefined;
  /**
   * @member {Number} startMinute
   */
  exports.prototype['startMinute'] = undefined;
  /**
   * @member {Number} stopHour
   */
  exports.prototype['stopHour'] = undefined;
  /**
   * @member {Number} stopMinute
   */
  exports.prototype['stopMinute'] = undefined;
  /**
   * @member {Boolean} onMonday
   */
  exports.prototype['onMonday'] = undefined;
  /**
   * @member {Boolean} onTuesday
   */
  exports.prototype['onTuesday'] = undefined;
  /**
   * @member {Boolean} onWednesday
   */
  exports.prototype['onWednesday'] = undefined;
  /**
   * @member {Boolean} onThursday
   */
  exports.prototype['onThursday'] = undefined;
  /**
   * @member {Boolean} onFriday
   */
  exports.prototype['onFriday'] = undefined;
  /**
   * @member {Boolean} onSaturday
   */
  exports.prototype['onSaturday'] = undefined;
  /**
   * @member {Boolean} onSunday
   */
  exports.prototype['onSunday'] = undefined;



  return exports;
}));


