/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CDevicePropertiesDTO', 'model/DeviceDTO', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CDevicePropertiesDTO'), require('./DeviceDTO'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.DevicePropertiesDTO = factory(root.MomitApi.ApiClient, root.MomitApi.CDevicePropertiesDTO, root.MomitApi.DeviceDTO, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, CDevicePropertiesDTO, DeviceDTO, RestLink) {
  'use strict';




  /**
   * The DevicePropertiesDTO model module.
   * @module model/DevicePropertiesDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>DevicePropertiesDTO</code>.
   * @alias module:model/DevicePropertiesDTO
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>DevicePropertiesDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DevicePropertiesDTO} obj Optional instance to populate.
   * @return {module:model/DevicePropertiesDTO} The populated <code>DevicePropertiesDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('serialNumber')) {
        obj['serialNumber'] = DeviceDTO.constructFromObject(data['serialNumber']);
      }
      if (data.hasOwnProperty('fkDevicePropertyTypeId')) {
        obj['fkDevicePropertyTypeId'] = CDevicePropertiesDTO.constructFromObject(data['fkDevicePropertyTypeId']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'String');
      }
      if (data.hasOwnProperty('additionalValue')) {
        obj['additionalValue'] = ApiClient.convertToType(data['additionalValue'], 'String');
      }
      if (data.hasOwnProperty('lastEdition')) {
        obj['lastEdition'] = ApiClient.convertToType(data['lastEdition'], 'Date');
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/DeviceDTO} serialNumber
   */
  exports.prototype['serialNumber'] = undefined;
  /**
   * @member {module:model/CDevicePropertiesDTO} fkDevicePropertyTypeId
   */
  exports.prototype['fkDevicePropertyTypeId'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} code
   */
  exports.prototype['code'] = undefined;
  /**
   * @member {String} value
   */
  exports.prototype['value'] = undefined;
  /**
   * @member {String} additionalValue
   */
  exports.prototype['additionalValue'] = undefined;
  /**
   * @member {Date} lastEdition
   */
  exports.prototype['lastEdition'] = undefined;
  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


