/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CDeviceStateDTO', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CDeviceStateDTO'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.DeviceAvailabityDTO = factory(root.MomitApi.ApiClient, root.MomitApi.CDeviceStateDTO, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, CDeviceStateDTO, RestLink) {
  'use strict';




  /**
   * The DeviceAvailabityDTO model module.
   * @module model/DeviceAvailabityDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>DeviceAvailabityDTO</code>.
   * @alias module:model/DeviceAvailabityDTO
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>DeviceAvailabityDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceAvailabityDTO} obj Optional instance to populate.
   * @return {module:model/DeviceAvailabityDTO} The populated <code>DeviceAvailabityDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('registered')) {
        obj['registered'] = ApiClient.convertToType(data['registered'], 'Boolean');
      }
      if (data.hasOwnProperty('connected')) {
        obj['connected'] = ApiClient.convertToType(data['connected'], 'Boolean');
      }
      if (data.hasOwnProperty('deviceState')) {
        obj['deviceState'] = CDeviceStateDTO.constructFromObject(data['deviceState']);
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} registered
   */
  exports.prototype['registered'] = undefined;
  /**
   * @member {Boolean} connected
   */
  exports.prototype['connected'] = undefined;
  /**
   * @member {module:model/CDeviceStateDTO} deviceState
   */
  exports.prototype['deviceState'] = undefined;
  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


