/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CDeviceStateDTO', 'model/CDeviceSubTypeDTO', 'model/CDeviceTypeDTO', 'model/CalendarDTO', 'model/DeviceDTO', 'model/DevicePropertiesDTO', 'model/InstallationDTO', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CDeviceStateDTO'), require('./CDeviceSubTypeDTO'), require('./CDeviceTypeDTO'), require('./CalendarDTO'), require('./DeviceDTO'), require('./DevicePropertiesDTO'), require('./InstallationDTO'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.DeviceDTO = factory(root.MomitApi.ApiClient, root.MomitApi.CDeviceStateDTO, root.MomitApi.CDeviceSubTypeDTO, root.MomitApi.CDeviceTypeDTO, root.MomitApi.CalendarDTO, root.MomitApi.DeviceDTO, root.MomitApi.DevicePropertiesDTO, root.MomitApi.InstallationDTO, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, CDeviceStateDTO, CDeviceSubTypeDTO, CDeviceTypeDTO, CalendarDTO, DeviceDTO, DevicePropertiesDTO, InstallationDTO, RestLink) {
  'use strict';




  /**
   * The DeviceDTO model module.
   * @module model/DeviceDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>DeviceDTO</code>.
   * @alias module:model/DeviceDTO
   * @class
   */
  var exports = function() {
    var _this = this;


















  };

  /**
   * Constructs a <code>DeviceDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceDTO} obj Optional instance to populate.
   * @return {module:model/DeviceDTO} The populated <code>DeviceDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('serialNumber')) {
        obj['serialNumber'] = ApiClient.convertToType(data['serialNumber'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = CDeviceTypeDTO.constructFromObject(data['type']);
      }
      if (data.hasOwnProperty('subType')) {
        obj['subType'] = CDeviceSubTypeDTO.constructFromObject(data['subType']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('gate')) {
        obj['gate'] = DeviceDTO.constructFromObject(data['gate']);
      }
      if (data.hasOwnProperty('installation')) {
        obj['installation'] = InstallationDTO.constructFromObject(data['installation']);
      }
      if (data.hasOwnProperty('registered')) {
        obj['registered'] = ApiClient.convertToType(data['registered'], 'Boolean');
      }
      if (data.hasOwnProperty('registerDate')) {
        obj['registerDate'] = ApiClient.convertToType(data['registerDate'], 'Date');
      }
      if (data.hasOwnProperty('calendar')) {
        obj['calendar'] = CalendarDTO.constructFromObject(data['calendar']);
      }
      if (data.hasOwnProperty('firmwareVersion')) {
        obj['firmwareVersion'] = ApiClient.convertToType(data['firmwareVersion'], 'Number');
      }
      if (data.hasOwnProperty('frequencyRadio')) {
        obj['frequencyRadio'] = ApiClient.convertToType(data['frequencyRadio'], 'String');
      }
      if (data.hasOwnProperty('hardwareVersion')) {
        obj['hardwareVersion'] = ApiClient.convertToType(data['hardwareVersion'], 'String');
      }
      if (data.hasOwnProperty('hardwareRevVersion')) {
        obj['hardwareRevVersion'] = ApiClient.convertToType(data['hardwareRevVersion'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = CDeviceStateDTO.constructFromObject(data['state']);
      }
      if (data.hasOwnProperty('endTimeState')) {
        obj['endTimeState'] = ApiClient.convertToType(data['endTimeState'], 'Date');
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
      if (data.hasOwnProperty('properties')) {
        obj['properties'] = ApiClient.convertToType(data['properties'], [DevicePropertiesDTO]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} serialNumber
   */
  exports.prototype['serialNumber'] = undefined;
  /**
   * @member {module:model/CDeviceTypeDTO} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {module:model/CDeviceSubTypeDTO} subType
   */
  exports.prototype['subType'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/DeviceDTO} gate
   */
  exports.prototype['gate'] = undefined;
  /**
   * @member {module:model/InstallationDTO} installation
   */
  exports.prototype['installation'] = undefined;
  /**
   * @member {Boolean} registered
   */
  exports.prototype['registered'] = undefined;
  /**
   * @member {Date} registerDate
   */
  exports.prototype['registerDate'] = undefined;
  /**
   * @member {module:model/CalendarDTO} calendar
   */
  exports.prototype['calendar'] = undefined;
  /**
   * @member {Number} firmwareVersion
   */
  exports.prototype['firmwareVersion'] = undefined;
  /**
   * @member {String} frequencyRadio
   */
  exports.prototype['frequencyRadio'] = undefined;
  /**
   * @member {String} hardwareVersion
   */
  exports.prototype['hardwareVersion'] = undefined;
  /**
   * @member {String} hardwareRevVersion
   */
  exports.prototype['hardwareRevVersion'] = undefined;
  /**
   * @member {module:model/CDeviceStateDTO} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {Date} endTimeState
   */
  exports.prototype['endTimeState'] = undefined;
  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Array.<module:model/DevicePropertiesDTO>} properties
   */
  exports.prototype['properties'] = undefined;



  return exports;
}));


