/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.HvacDTO = factory(root.MomitApi.ApiClient, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, RestLink) {
  'use strict';




  /**
   * The HvacDTO model module.
   * @module model/HvacDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>HvacDTO</code>.
   * @alias module:model/HvacDTO
   * @class
   */
  var exports = function() {
    var _this = this;

























  };

  /**
   * Constructs a <code>HvacDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HvacDTO} obj Optional instance to populate.
   * @return {module:model/HvacDTO} The populated <code>HvacDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('inertial')) {
        obj['inertial'] = ApiClient.convertToType(data['inertial'], 'Boolean');
      }
      if (data.hasOwnProperty('systemType')) {
        obj['systemType'] = ApiClient.convertToType(data['systemType'], 'String');
      }
      if (data.hasOwnProperty('respInfo')) {
        obj['respInfo'] = ApiClient.convertToType(data['respInfo'], 'String');
      }
      if (data.hasOwnProperty('powerSupplyType')) {
        obj['powerSupplyType'] = ApiClient.convertToType(data['powerSupplyType'], 'Number');
      }
      if (data.hasOwnProperty('coolingType')) {
        obj['coolingType'] = ApiClient.convertToType(data['coolingType'], 'Number');
      }
      if (data.hasOwnProperty('heatingType')) {
        obj['heatingType'] = ApiClient.convertToType(data['heatingType'], 'Number');
      }
      if (data.hasOwnProperty('fanType')) {
        obj['fanType'] = ApiClient.convertToType(data['fanType'], 'Number');
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
      if (data.hasOwnProperty('obCool')) {
        obj['obCool'] = ApiClient.convertToType(data['obCool'], 'Boolean');
      }
      if (data.hasOwnProperty('gh')) {
        obj['gh'] = ApiClient.convertToType(data['gh'], 'Boolean');
      }
      if (data.hasOwnProperty('gm')) {
        obj['gm'] = ApiClient.convertToType(data['gm'], 'Boolean');
      }
      if (data.hasOwnProperty('auxE')) {
        obj['auxE'] = ApiClient.convertToType(data['auxE'], 'Boolean');
      }
      if (data.hasOwnProperty('ob')) {
        obj['ob'] = ApiClient.convertToType(data['ob'], 'Boolean');
      }
      if (data.hasOwnProperty('b')) {
        obj['b'] = ApiClient.convertToType(data['b'], 'Boolean');
      }
      if (data.hasOwnProperty('o')) {
        obj['o'] = ApiClient.convertToType(data['o'], 'Boolean');
      }
      if (data.hasOwnProperty('ggl')) {
        obj['ggl'] = ApiClient.convertToType(data['ggl'], 'Boolean');
      }
      if (data.hasOwnProperty('y2')) {
        obj['y2'] = ApiClient.convertToType(data['y2'], 'Boolean');
      }
      if (data.hasOwnProperty('yy1')) {
        obj['yy1'] = ApiClient.convertToType(data['yy1'], 'Boolean');
      }
      if (data.hasOwnProperty('w2')) {
        obj['w2'] = ApiClient.convertToType(data['w2'], 'Boolean');
      }
      if (data.hasOwnProperty('ww1')) {
        obj['ww1'] = ApiClient.convertToType(data['ww1'], 'Boolean');
      }
      if (data.hasOwnProperty('rc')) {
        obj['rc'] = ApiClient.convertToType(data['rc'], 'Boolean');
      }
      if (data.hasOwnProperty('rrh')) {
        obj['rrh'] = ApiClient.convertToType(data['rrh'], 'Boolean');
      }
      if (data.hasOwnProperty('c')) {
        obj['c'] = ApiClient.convertToType(data['c'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Boolean} inertial
   */
  exports.prototype['inertial'] = undefined;
  /**
   * @member {String} systemType
   */
  exports.prototype['systemType'] = undefined;
  /**
   * @member {String} respInfo
   */
  exports.prototype['respInfo'] = undefined;
  /**
   * @member {Number} powerSupplyType
   */
  exports.prototype['powerSupplyType'] = undefined;
  /**
   * @member {Number} coolingType
   */
  exports.prototype['coolingType'] = undefined;
  /**
   * @member {Number} heatingType
   */
  exports.prototype['heatingType'] = undefined;
  /**
   * @member {Number} fanType
   */
  exports.prototype['fanType'] = undefined;
  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Boolean} obCool
   */
  exports.prototype['obCool'] = undefined;
  /**
   * @member {Boolean} gh
   */
  exports.prototype['gh'] = undefined;
  /**
   * @member {Boolean} gm
   */
  exports.prototype['gm'] = undefined;
  /**
   * @member {Boolean} auxE
   */
  exports.prototype['auxE'] = undefined;
  /**
   * @member {Boolean} ob
   */
  exports.prototype['ob'] = undefined;
  /**
   * @member {Boolean} b
   */
  exports.prototype['b'] = undefined;
  /**
   * @member {Boolean} o
   */
  exports.prototype['o'] = undefined;
  /**
   * @member {Boolean} ggl
   */
  exports.prototype['ggl'] = undefined;
  /**
   * @member {Boolean} y2
   */
  exports.prototype['y2'] = undefined;
  /**
   * @member {Boolean} yy1
   */
  exports.prototype['yy1'] = undefined;
  /**
   * @member {Boolean} w2
   */
  exports.prototype['w2'] = undefined;
  /**
   * @member {Boolean} ww1
   */
  exports.prototype['ww1'] = undefined;
  /**
   * @member {Boolean} rc
   */
  exports.prototype['rc'] = undefined;
  /**
   * @member {Boolean} rrh
   */
  exports.prototype['rrh'] = undefined;
  /**
   * @member {Boolean} c
   */
  exports.prototype['c'] = undefined;



  return exports;
}));


