/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CountryDTO', 'model/RestLink', 'model/TimeZoneDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CountryDTO'), require('./RestLink'), require('./TimeZoneDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.InstallationDTO = factory(root.MomitApi.ApiClient, root.MomitApi.CountryDTO, root.MomitApi.RestLink, root.MomitApi.TimeZoneDTO);
  }
}(this, function(ApiClient, CountryDTO, RestLink, TimeZoneDTO) {
  'use strict';




  /**
   * The InstallationDTO model module.
   * @module model/InstallationDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>InstallationDTO</code>.
   * @alias module:model/InstallationDTO
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>InstallationDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InstallationDTO} obj Optional instance to populate.
   * @return {module:model/InstallationDTO} The populated <code>InstallationDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
      if (data.hasOwnProperty('postalCode')) {
        obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'String');
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = CountryDTO.constructFromObject(data['country']);
      }
      if (data.hasOwnProperty('timeZone')) {
        obj['timeZone'] = TimeZoneDTO.constructFromObject(data['timeZone']);
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
      if (data.hasOwnProperty('radioGeolocation')) {
        obj['radioGeolocation'] = ApiClient.convertToType(data['radioGeolocation'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {String} postalCode
   */
  exports.prototype['postalCode'] = undefined;
  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {String} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * @member {String} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * @member {module:model/CountryDTO} country
   */
  exports.prototype['country'] = undefined;
  /**
   * @member {module:model/TimeZoneDTO} timeZone
   */
  exports.prototype['timeZone'] = undefined;
  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Number} radioGeolocation
   */
  exports.prototype['radioGeolocation'] = undefined;



  return exports;
}));


