/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InstallationDTO', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InstallationDTO'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.InvitationDTO = factory(root.MomitApi.ApiClient, root.MomitApi.InstallationDTO, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, InstallationDTO, RestLink) {
  'use strict';




  /**
   * The InvitationDTO model module.
   * @module model/InvitationDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>InvitationDTO</code>.
   * @alias module:model/InvitationDTO
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>InvitationDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InvitationDTO} obj Optional instance to populate.
   * @return {module:model/InvitationDTO} The populated <code>InvitationDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('installation')) {
        obj['installation'] = InstallationDTO.constructFromObject(data['installation']);
      }
      if (data.hasOwnProperty('invitationDate')) {
        obj['invitationDate'] = ApiClient.convertToType(data['invitationDate'], 'Date');
      }
      if (data.hasOwnProperty('invitationToken')) {
        obj['invitationToken'] = ApiClient.convertToType(data['invitationToken'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {module:model/InstallationDTO} installation
   */
  exports.prototype['installation'] = undefined;
  /**
   * @member {Date} invitationDate
   */
  exports.prototype['invitationDate'] = undefined;
  /**
   * @member {String} invitationToken
   */
  exports.prototype['invitationToken'] = undefined;



  return exports;
}));


