/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MyBudgetDeviceDTO', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MyBudgetDeviceDTO'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.MyBudgetPredictionDTO = factory(root.MomitApi.ApiClient, root.MomitApi.MyBudgetDeviceDTO, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, MyBudgetDeviceDTO, RestLink) {
  'use strict';




  /**
   * The MyBudgetPredictionDTO model module.
   * @module model/MyBudgetPredictionDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>MyBudgetPredictionDTO</code>.
   * @alias module:model/MyBudgetPredictionDTO
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>MyBudgetPredictionDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MyBudgetPredictionDTO} obj Optional instance to populate.
   * @return {module:model/MyBudgetPredictionDTO} The populated <code>MyBudgetPredictionDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
      if (data.hasOwnProperty('serialNumber')) {
        obj['serialNumber'] = MyBudgetDeviceDTO.constructFromObject(data['serialNumber']);
      }
      if (data.hasOwnProperty('from')) {
        obj['from'] = ApiClient.convertToType(data['from'], 'Date');
      }
      if (data.hasOwnProperty('until')) {
        obj['until'] = ApiClient.convertToType(data['until'], 'Date');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {module:model/MyBudgetDeviceDTO} serialNumber
   */
  exports.prototype['serialNumber'] = undefined;
  /**
   * @member {Date} from
   */
  exports.prototype['from'] = undefined;
  /**
   * @member {Date} until
   */
  exports.prototype['until'] = undefined;
  /**
   * @member {String} value
   */
  exports.prototype['value'] = undefined;



  return exports;
}));


