/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MyBudgetRateDTO', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MyBudgetRateDTO'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.MyBudgetRatePeriodDTO = factory(root.MomitApi.ApiClient, root.MomitApi.MyBudgetRateDTO, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, MyBudgetRateDTO, RestLink) {
  'use strict';




  /**
   * The MyBudgetRatePeriodDTO model module.
   * @module model/MyBudgetRatePeriodDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>MyBudgetRatePeriodDTO</code>.
   * @alias module:model/MyBudgetRatePeriodDTO
   * @class
   */
  var exports = function() {
    var _this = this;


















  };

  /**
   * Constructs a <code>MyBudgetRatePeriodDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MyBudgetRatePeriodDTO} obj Optional instance to populate.
   * @return {module:model/MyBudgetRatePeriodDTO} The populated <code>MyBudgetRatePeriodDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
      if (data.hasOwnProperty('ratePeriodId')) {
        obj['ratePeriodId'] = ApiClient.convertToType(data['ratePeriodId'], 'Number');
      }
      if (data.hasOwnProperty('rate')) {
        obj['rate'] = MyBudgetRateDTO.constructFromObject(data['rate']);
      }
      if (data.hasOwnProperty('cost')) {
        obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
      }
      if (data.hasOwnProperty('startHour')) {
        obj['startHour'] = ApiClient.convertToType(data['startHour'], 'Blob');
      }
      if (data.hasOwnProperty('startMin')) {
        obj['startMin'] = ApiClient.convertToType(data['startMin'], 'Blob');
      }
      if (data.hasOwnProperty('stopHour')) {
        obj['stopHour'] = ApiClient.convertToType(data['stopHour'], 'Blob');
      }
      if (data.hasOwnProperty('stopMin')) {
        obj['stopMin'] = ApiClient.convertToType(data['stopMin'], 'Blob');
      }
      if (data.hasOwnProperty('mon')) {
        obj['mon'] = ApiClient.convertToType(data['mon'], 'Blob');
      }
      if (data.hasOwnProperty('tue')) {
        obj['tue'] = ApiClient.convertToType(data['tue'], 'Blob');
      }
      if (data.hasOwnProperty('wed')) {
        obj['wed'] = ApiClient.convertToType(data['wed'], 'Blob');
      }
      if (data.hasOwnProperty('thu')) {
        obj['thu'] = ApiClient.convertToType(data['thu'], 'Blob');
      }
      if (data.hasOwnProperty('fri')) {
        obj['fri'] = ApiClient.convertToType(data['fri'], 'Blob');
      }
      if (data.hasOwnProperty('sat')) {
        obj['sat'] = ApiClient.convertToType(data['sat'], 'Blob');
      }
      if (data.hasOwnProperty('sun')) {
        obj['sun'] = ApiClient.convertToType(data['sun'], 'Blob');
      }
      if (data.hasOwnProperty('invoiceType')) {
        obj['invoiceType'] = ApiClient.convertToType(data['invoiceType'], 'Blob');
      }
      if (data.hasOwnProperty('invoiceDay')) {
        obj['invoiceDay'] = ApiClient.convertToType(data['invoiceDay'], 'Blob');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Number} ratePeriodId
   */
  exports.prototype['ratePeriodId'] = undefined;
  /**
   * @member {module:model/MyBudgetRateDTO} rate
   */
  exports.prototype['rate'] = undefined;
  /**
   * @member {Number} cost
   */
  exports.prototype['cost'] = undefined;
  /**
   * @member {Blob} startHour
   */
  exports.prototype['startHour'] = undefined;
  /**
   * @member {Blob} startMin
   */
  exports.prototype['startMin'] = undefined;
  /**
   * @member {Blob} stopHour
   */
  exports.prototype['stopHour'] = undefined;
  /**
   * @member {Blob} stopMin
   */
  exports.prototype['stopMin'] = undefined;
  /**
   * @member {Blob} mon
   */
  exports.prototype['mon'] = undefined;
  /**
   * @member {Blob} tue
   */
  exports.prototype['tue'] = undefined;
  /**
   * @member {Blob} wed
   */
  exports.prototype['wed'] = undefined;
  /**
   * @member {Blob} thu
   */
  exports.prototype['thu'] = undefined;
  /**
   * @member {Blob} fri
   */
  exports.prototype['fri'] = undefined;
  /**
   * @member {Blob} sat
   */
  exports.prototype['sat'] = undefined;
  /**
   * @member {Blob} sun
   */
  exports.prototype['sun'] = undefined;
  /**
   * @member {Blob} invoiceType
   */
  exports.prototype['invoiceType'] = undefined;
  /**
   * @member {Blob} invoiceDay
   */
  exports.prototype['invoiceDay'] = undefined;



  return exports;
}));


