/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MyBudgetCalendarDTO', 'model/MyBudgetHvacTypeDTO', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MyBudgetCalendarDTO'), require('./MyBudgetHvacTypeDTO'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.MyBudgetDeviceDTO = factory(root.MomitApi.ApiClient, root.MomitApi.MyBudgetCalendarDTO, root.MomitApi.MyBudgetHvacTypeDTO, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, MyBudgetCalendarDTO, MyBudgetHvacTypeDTO, RestLink) {
  'use strict';




  /**
   * The MyBudgetDeviceDTO model module.
   * @module model/MyBudgetDeviceDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>MyBudgetDeviceDTO</code>.
   * @alias module:model/MyBudgetDeviceDTO
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>MyBudgetDeviceDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MyBudgetDeviceDTO} obj Optional instance to populate.
   * @return {module:model/MyBudgetDeviceDTO} The populated <code>MyBudgetDeviceDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
      if (data.hasOwnProperty('serialNumber')) {
        obj['serialNumber'] = ApiClient.convertToType(data['serialNumber'], 'Number');
      }
      if (data.hasOwnProperty('hvacType')) {
        obj['hvacType'] = MyBudgetHvacTypeDTO.constructFromObject(data['hvacType']);
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
      }
      if (data.hasOwnProperty('goalCost')) {
        obj['goalCost'] = ApiClient.convertToType(data['goalCost'], 'Number');
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'Date');
      }
      if (data.hasOwnProperty('timeZone')) {
        obj['timeZone'] = ApiClient.convertToType(data['timeZone'], 'String');
      }
      if (data.hasOwnProperty('calendar')) {
        obj['calendar'] = MyBudgetCalendarDTO.constructFromObject(data['calendar']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Number} serialNumber
   */
  exports.prototype['serialNumber'] = undefined;
  /**
   * @member {module:model/MyBudgetHvacTypeDTO} hvacType
   */
  exports.prototype['hvacType'] = undefined;
  /**
   * @member {Number} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * @member {Number} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * @member {Number} goalCost
   */
  exports.prototype['goalCost'] = undefined;
  /**
   * @member {Date} created
   */
  exports.prototype['created'] = undefined;
  /**
   * @member {String} timeZone
   */
  exports.prototype['timeZone'] = undefined;
  /**
   * @member {module:model/MyBudgetCalendarDTO} calendar
   */
  exports.prototype['calendar'] = undefined;



  return exports;
}));


