/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.MyBudgetHvacTypeDTO = factory(root.MomitApi.ApiClient, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, RestLink) {
  'use strict';




  /**
   * The MyBudgetHvacTypeDTO model module.
   * @module model/MyBudgetHvacTypeDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>MyBudgetHvacTypeDTO</code>.
   * @alias module:model/MyBudgetHvacTypeDTO
   * @class
   */
  var exports = function() {
    var _this = this;


























  };

  /**
   * Constructs a <code>MyBudgetHvacTypeDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MyBudgetHvacTypeDTO} obj Optional instance to populate.
   * @return {module:model/MyBudgetHvacTypeDTO} The populated <code>MyBudgetHvacTypeDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
      if (data.hasOwnProperty('hvacTypeId')) {
        obj['hvacTypeId'] = ApiClient.convertToType(data['hvacTypeId'], 'Number');
      }
      if (data.hasOwnProperty('inertial')) {
        obj['inertial'] = ApiClient.convertToType(data['inertial'], 'Boolean');
      }
      if (data.hasOwnProperty('releOBCool')) {
        obj['releOBCool'] = ApiClient.convertToType(data['releOBCool'], 'Boolean');
      }
      if (data.hasOwnProperty('releGH')) {
        obj['releGH'] = ApiClient.convertToType(data['releGH'], 'Boolean');
      }
      if (data.hasOwnProperty('releGM')) {
        obj['releGM'] = ApiClient.convertToType(data['releGM'], 'Boolean');
      }
      if (data.hasOwnProperty('releAUXE')) {
        obj['releAUXE'] = ApiClient.convertToType(data['releAUXE'], 'Boolean');
      }
      if (data.hasOwnProperty('releOB')) {
        obj['releOB'] = ApiClient.convertToType(data['releOB'], 'Boolean');
      }
      if (data.hasOwnProperty('releB')) {
        obj['releB'] = ApiClient.convertToType(data['releB'], 'Boolean');
      }
      if (data.hasOwnProperty('releO')) {
        obj['releO'] = ApiClient.convertToType(data['releO'], 'Boolean');
      }
      if (data.hasOwnProperty('releGGL')) {
        obj['releGGL'] = ApiClient.convertToType(data['releGGL'], 'Boolean');
      }
      if (data.hasOwnProperty('releY2')) {
        obj['releY2'] = ApiClient.convertToType(data['releY2'], 'Boolean');
      }
      if (data.hasOwnProperty('releYY1')) {
        obj['releYY1'] = ApiClient.convertToType(data['releYY1'], 'Boolean');
      }
      if (data.hasOwnProperty('releW2')) {
        obj['releW2'] = ApiClient.convertToType(data['releW2'], 'Boolean');
      }
      if (data.hasOwnProperty('releWW1')) {
        obj['releWW1'] = ApiClient.convertToType(data['releWW1'], 'Boolean');
      }
      if (data.hasOwnProperty('releRC')) {
        obj['releRC'] = ApiClient.convertToType(data['releRC'], 'Boolean');
      }
      if (data.hasOwnProperty('releRRH')) {
        obj['releRRH'] = ApiClient.convertToType(data['releRRH'], 'Boolean');
      }
      if (data.hasOwnProperty('releC')) {
        obj['releC'] = ApiClient.convertToType(data['releC'], 'Boolean');
      }
      if (data.hasOwnProperty('systemType')) {
        obj['systemType'] = ApiClient.convertToType(data['systemType'], 'String');
      }
      if (data.hasOwnProperty('respInfo')) {
        obj['respInfo'] = ApiClient.convertToType(data['respInfo'], 'String');
      }
      if (data.hasOwnProperty('powerSupplyType')) {
        obj['powerSupplyType'] = ApiClient.convertToType(data['powerSupplyType'], 'Number');
      }
      if (data.hasOwnProperty('coolingType')) {
        obj['coolingType'] = ApiClient.convertToType(data['coolingType'], 'Number');
      }
      if (data.hasOwnProperty('heatingType')) {
        obj['heatingType'] = ApiClient.convertToType(data['heatingType'], 'Number');
      }
      if (data.hasOwnProperty('fanType')) {
        obj['fanType'] = ApiClient.convertToType(data['fanType'], 'Number');
      }
      if (data.hasOwnProperty('defaultTimeBlocker')) {
        obj['defaultTimeBlocker'] = ApiClient.convertToType(data['defaultTimeBlocker'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Number} hvacTypeId
   */
  exports.prototype['hvacTypeId'] = undefined;
  /**
   * @member {Boolean} inertial
   */
  exports.prototype['inertial'] = undefined;
  /**
   * @member {Boolean} releOBCool
   */
  exports.prototype['releOBCool'] = undefined;
  /**
   * @member {Boolean} releGH
   */
  exports.prototype['releGH'] = undefined;
  /**
   * @member {Boolean} releGM
   */
  exports.prototype['releGM'] = undefined;
  /**
   * @member {Boolean} releAUXE
   */
  exports.prototype['releAUXE'] = undefined;
  /**
   * @member {Boolean} releOB
   */
  exports.prototype['releOB'] = undefined;
  /**
   * @member {Boolean} releB
   */
  exports.prototype['releB'] = undefined;
  /**
   * @member {Boolean} releO
   */
  exports.prototype['releO'] = undefined;
  /**
   * @member {Boolean} releGGL
   */
  exports.prototype['releGGL'] = undefined;
  /**
   * @member {Boolean} releY2
   */
  exports.prototype['releY2'] = undefined;
  /**
   * @member {Boolean} releYY1
   */
  exports.prototype['releYY1'] = undefined;
  /**
   * @member {Boolean} releW2
   */
  exports.prototype['releW2'] = undefined;
  /**
   * @member {Boolean} releWW1
   */
  exports.prototype['releWW1'] = undefined;
  /**
   * @member {Boolean} releRC
   */
  exports.prototype['releRC'] = undefined;
  /**
   * @member {Boolean} releRRH
   */
  exports.prototype['releRRH'] = undefined;
  /**
   * @member {Boolean} releC
   */
  exports.prototype['releC'] = undefined;
  /**
   * @member {String} systemType
   */
  exports.prototype['systemType'] = undefined;
  /**
   * @member {String} respInfo
   */
  exports.prototype['respInfo'] = undefined;
  /**
   * @member {Number} powerSupplyType
   */
  exports.prototype['powerSupplyType'] = undefined;
  /**
   * @member {Number} coolingType
   */
  exports.prototype['coolingType'] = undefined;
  /**
   * @member {Number} heatingType
   */
  exports.prototype['heatingType'] = undefined;
  /**
   * @member {Number} fanType
   */
  exports.prototype['fanType'] = undefined;
  /**
   * @member {Number} defaultTimeBlocker
   */
  exports.prototype['defaultTimeBlocker'] = undefined;



  return exports;
}));


