/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.RestLink = factory(root.MomitApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RestLink model module.
   * @module model/RestLink
   * @version 1.0
   */

  /**
   * Constructs a new <code>RestLink</code>.
   * @alias module:model/RestLink
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>RestLink</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RestLink} obj Optional instance to populate.
   * @return {module:model/RestLink} The populated <code>RestLink</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], Object);
      }
      if (data.hasOwnProperty('rel')) {
        obj['rel'] = ApiClient.convertToType(data['rel'], 'String');
      }
      if (data.hasOwnProperty('link')) {
        obj['link'] = ApiClient.convertToType(data['link'], 'String');
      }
      if (data.hasOwnProperty('inputParams')) {
        obj['inputParams'] = ApiClient.convertToType(data['inputParams'], 'String');
      }
      if (data.hasOwnProperty('options')) {
        obj['options'] = ApiClient.convertToType(data['options'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Object} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} rel
   */
  exports.prototype['rel'] = undefined;
  /**
   * @member {String} link
   */
  exports.prototype['link'] = undefined;
  /**
   * @member {String} inputParams
   */
  exports.prototype['inputParams'] = undefined;
  /**
   * @member {Array.<String>} options
   */
  exports.prototype['options'] = undefined;



  return exports;
}));


