/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RestLink', 'model/TimeZoneDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RestLink'), require('./TimeZoneDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.StatsDTO = factory(root.MomitApi.ApiClient, root.MomitApi.RestLink, root.MomitApi.TimeZoneDTO);
  }
}(this, function(ApiClient, RestLink, TimeZoneDTO) {
  'use strict';




  /**
   * The StatsDTO model module.
   * @module model/StatsDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>StatsDTO</code>.
   * @alias module:model/StatsDTO
   * @class
   */
  var exports = function() {
    var _this = this;
























  };

  /**
   * Constructs a <code>StatsDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StatsDTO} obj Optional instance to populate.
   * @return {module:model/StatsDTO} The populated <code>StatsDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('year')) {
        obj['year'] = ApiClient.convertToType(data['year'], 'Number');
      }
      if (data.hasOwnProperty('month')) {
        obj['month'] = ApiClient.convertToType(data['month'], 'Number');
      }
      if (data.hasOwnProperty('day')) {
        obj['day'] = ApiClient.convertToType(data['day'], 'Number');
      }
      if (data.hasOwnProperty('isoWeek')) {
        obj['isoWeek'] = ApiClient.convertToType(data['isoWeek'], 'Number');
      }
      if (data.hasOwnProperty('isoDayWeek')) {
        obj['isoDayWeek'] = ApiClient.convertToType(data['isoDayWeek'], 'Number');
      }
      if (data.hasOwnProperty('hour')) {
        obj['hour'] = ApiClient.convertToType(data['hour'], 'Number');
      }
      if (data.hasOwnProperty('min')) {
        obj['min'] = ApiClient.convertToType(data['min'], 'Number');
      }
      if (data.hasOwnProperty('deviceId')) {
        obj['deviceId'] = ApiClient.convertToType(data['deviceId'], 'Number');
      }
      if (data.hasOwnProperty('timeZone')) {
        obj['timeZone'] = TimeZoneDTO.constructFromObject(data['timeZone']);
      }
      if (data.hasOwnProperty('timeStamp')) {
        obj['timeStamp'] = ApiClient.convertToType(data['timeStamp'], 'Number');
      }
      if (data.hasOwnProperty('temperatureIn')) {
        obj['temperatureIn'] = ApiClient.convertToType(data['temperatureIn'], 'Number');
      }
      if (data.hasOwnProperty('temperatureOut')) {
        obj['temperatureOut'] = ApiClient.convertToType(data['temperatureOut'], 'Number');
      }
      if (data.hasOwnProperty('humidityIn')) {
        obj['humidityIn'] = ApiClient.convertToType(data['humidityIn'], 'Number');
      }
      if (data.hasOwnProperty('humidityOut')) {
        obj['humidityOut'] = ApiClient.convertToType(data['humidityOut'], 'Number');
      }
      if (data.hasOwnProperty('releAuxE')) {
        obj['releAuxE'] = ApiClient.convertToType(data['releAuxE'], 'Boolean');
      }
      if (data.hasOwnProperty('releOB')) {
        obj['releOB'] = ApiClient.convertToType(data['releOB'], 'Boolean');
      }
      if (data.hasOwnProperty('releGGL')) {
        obj['releGGL'] = ApiClient.convertToType(data['releGGL'], 'Boolean');
      }
      if (data.hasOwnProperty('releY2')) {
        obj['releY2'] = ApiClient.convertToType(data['releY2'], 'Boolean');
      }
      if (data.hasOwnProperty('releYY1')) {
        obj['releYY1'] = ApiClient.convertToType(data['releYY1'], 'Boolean');
      }
      if (data.hasOwnProperty('releW2')) {
        obj['releW2'] = ApiClient.convertToType(data['releW2'], 'Boolean');
      }
      if (data.hasOwnProperty('releWW1')) {
        obj['releWW1'] = ApiClient.convertToType(data['releWW1'], 'Boolean');
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} year
   */
  exports.prototype['year'] = undefined;
  /**
   * @member {Number} month
   */
  exports.prototype['month'] = undefined;
  /**
   * @member {Number} day
   */
  exports.prototype['day'] = undefined;
  /**
   * @member {Number} isoWeek
   */
  exports.prototype['isoWeek'] = undefined;
  /**
   * @member {Number} isoDayWeek
   */
  exports.prototype['isoDayWeek'] = undefined;
  /**
   * @member {Number} hour
   */
  exports.prototype['hour'] = undefined;
  /**
   * @member {Number} min
   */
  exports.prototype['min'] = undefined;
  /**
   * @member {Number} deviceId
   */
  exports.prototype['deviceId'] = undefined;
  /**
   * @member {module:model/TimeZoneDTO} timeZone
   */
  exports.prototype['timeZone'] = undefined;
  /**
   * @member {Number} timeStamp
   */
  exports.prototype['timeStamp'] = undefined;
  /**
   * @member {Number} temperatureIn
   */
  exports.prototype['temperatureIn'] = undefined;
  /**
   * @member {Number} temperatureOut
   */
  exports.prototype['temperatureOut'] = undefined;
  /**
   * @member {Number} humidityIn
   */
  exports.prototype['humidityIn'] = undefined;
  /**
   * @member {Number} humidityOut
   */
  exports.prototype['humidityOut'] = undefined;
  /**
   * @member {Boolean} releAuxE
   */
  exports.prototype['releAuxE'] = undefined;
  /**
   * @member {Boolean} releOB
   */
  exports.prototype['releOB'] = undefined;
  /**
   * @member {Boolean} releGGL
   */
  exports.prototype['releGGL'] = undefined;
  /**
   * @member {Boolean} releY2
   */
  exports.prototype['releY2'] = undefined;
  /**
   * @member {Boolean} releYY1
   */
  exports.prototype['releYY1'] = undefined;
  /**
   * @member {Boolean} releW2
   */
  exports.prototype['releW2'] = undefined;
  /**
   * @member {Boolean} releWW1
   */
  exports.prototype['releWW1'] = undefined;
  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


