/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CCurrencyDTO', 'model/RestLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CCurrencyDTO'), require('./RestLink'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.UserPreferencesDTO = factory(root.MomitApi.ApiClient, root.MomitApi.CCurrencyDTO, root.MomitApi.RestLink);
  }
}(this, function(ApiClient, CCurrencyDTO, RestLink) {
  'use strict';




  /**
   * The UserPreferencesDTO model module.
   * @module model/UserPreferencesDTO
   * @version 1.0
   */

  /**
   * Constructs a new <code>UserPreferencesDTO</code>.
   * @alias module:model/UserPreferencesDTO
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>UserPreferencesDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserPreferencesDTO} obj Optional instance to populate.
   * @return {module:model/UserPreferencesDTO} The populated <code>UserPreferencesDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [RestLink]);
      }
      if (data.hasOwnProperty('numberFormat')) {
        obj['numberFormat'] = ApiClient.convertToType(data['numberFormat'], 'String');
      }
      if (data.hasOwnProperty('dateFormat')) {
        obj['dateFormat'] = ApiClient.convertToType(data['dateFormat'], 'String');
      }
      if (data.hasOwnProperty('hourFormat')) {
        obj['hourFormat'] = ApiClient.convertToType(data['hourFormat'], 'String');
      }
      if (data.hasOwnProperty('firstDayWeek')) {
        obj['firstDayWeek'] = ApiClient.convertToType(data['firstDayWeek'], 'String');
      }
      if (data.hasOwnProperty('distance')) {
        obj['distance'] = ApiClient.convertToType(data['distance'], 'String');
      }
      if (data.hasOwnProperty('temperature')) {
        obj['temperature'] = ApiClient.convertToType(data['temperature'], 'String');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = CCurrencyDTO.constructFromObject(data['currency']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RestLink>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {String} numberFormat
   */
  exports.prototype['numberFormat'] = undefined;
  /**
   * @member {String} dateFormat
   */
  exports.prototype['dateFormat'] = undefined;
  /**
   * @member {String} hourFormat
   */
  exports.prototype['hourFormat'] = undefined;
  /**
   * @member {String} firstDayWeek
   */
  exports.prototype['firstDayWeek'] = undefined;
  /**
   * @member {String} distance
   */
  exports.prototype['distance'] = undefined;
  /**
   * @member {String} temperature
   */
  exports.prototype['temperature'] = undefined;
  /**
   * @member {module:model/CCurrencyDTO} currency
   */
  exports.prototype['currency'] = undefined;



  return exports;
}));


