/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.DeviceCommonApi = factory(root.MomitApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * DeviceCommon service.
   * @module api/DeviceCommonApi
   * @version 1.0
   */

  /**
   * Constructs a new DeviceCommonApi. 
   * @alias module:api/DeviceCommonApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the deviceTypes operation.
     * @callback module:api/DeviceCommonApi~deviceTypesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This method returns the list of device types availables in the API
     * xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
     * @param {module:api/DeviceCommonApi~deviceTypesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deviceTypes = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key', 'token'];
      var contentTypes = [];
      var accepts = ['text/plain', 'application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/deviceCatalogs/deviceType', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getModeById operation.
     * @callback module:api/DeviceCommonApi~getModeByIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This method returns device mode request by id
     * xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
     * @param {Number} id Id of the mode
     * @param {module:api/DeviceCommonApi~getModeByIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getModeById = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getModeById");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key', 'token'];
      var contentTypes = [];
      var accepts = ['text/plain', 'application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/deviceCatalogs/mode/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getProperties operation.
     * @callback module:api/DeviceCommonApi~getPropertiesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This method returns all properties available in the API
     * xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
     * @param {module:api/DeviceCommonApi~getPropertiesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getProperties = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key', 'token'];
      var contentTypes = [];
      var accepts = ['text/plain', 'application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/deviceCatalogs/properties', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getStateById operation.
     * @callback module:api/DeviceCommonApi~getStateByIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This method returns device state request by id
     * xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
     * @param {Number} id Id of the state
     * @param {module:api/DeviceCommonApi~getStateByIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getStateById = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getStateById");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key', 'token'];
      var contentTypes = [];
      var accepts = ['text/plain', 'application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/deviceCatalogs/state/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
