/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.HvacApi = factory(root.MomitApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Hvac service.
   * @module api/HvacApi
   * @version 1.0
   */

  /**
   * Constructs a new HvacApi. 
   * @alias module:api/HvacApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getAll operation.
     * @callback module:api/HvacApi~getAllCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This method returns the hvac appropiate for the parameters request
     * xxxxxxxxxxxxxxxxxx
     * @param {module:api/HvacApi~getAllCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getAll = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key', 'token'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/hvac', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getById operation.
     * @callback module:api/HvacApi~getByIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This method returns a hvac request by systemtype
     * xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
     * @param {String} systemType Id of the hvac
     * @param {module:api/HvacApi~getByIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getById = function(systemType, callback) {
      var postBody = null;

      // verify the required parameter 'systemType' is set
      if (systemType === undefined || systemType === null) {
        throw new Error("Missing the required parameter 'systemType' when calling getById");
      }


      var pathParams = {
        'systemType': systemType
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key', 'token'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/hvac/systemtype/{systemType}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getWireList operation.
     * @callback module:api/HvacApi~getWireListCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This method returns the list of hvac 
     * xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.wirelist List of reles for systemtype
     * @param {module:api/HvacApi~getWireListCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getWireList = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'wirelist': this.apiClient.buildCollectionParam(opts['wirelist'], 'multi')
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key', 'token'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/hvac/wirelist', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
