/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.IntentredirectionApi = factory(root.MomitApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Intentredirection service.
   * @module api/IntentredirectionApi
   * @version 1.0
   */

  /**
   * Constructs a new IntentredirectionApi. 
   * @alias module:api/IntentredirectionApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getRedirect operation.
     * @callback module:api/IntentredirectionApi~getRedirectCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This method redirect to intent url for app mobile
     * xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
     * @param {String} action Action for redirect
     * @param {Object} opts Optional parameters
     * @param {String} opts.scheme Scheme for for redirect
     * @param {String} opts.packageName Package for redirect
     * @param {String} opts.userResetToken Usertoken for redirect
     * @param {String} opts.invitationToken Invitationtoken for redirect
     * @param {String} opts.invitationId Invitation id for redirect
     * @param {String} opts.state State for redirect
     * @param {module:api/IntentredirectionApi~getRedirectCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getRedirect = function(action, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'action' is set
      if (action === undefined || action === null) {
        throw new Error("Missing the required parameter 'action' when calling getRedirect");
      }


      var pathParams = {
      };
      var queryParams = {
        'action': action,
        'scheme': opts['scheme'],
        'packageName': opts['packageName'],
        'userResetToken': opts['userResetToken'],
        'invitationToken': opts['invitationToken'],
        'invitationId': opts['invitationId'],
        'state': opts['state']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/intentredirecction', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
