/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InvitationDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InvitationDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.InvitationApi = factory(root.MomitApi.ApiClient, root.MomitApi.InvitationDTO);
  }
}(this, function(ApiClient, InvitationDTO) {
  'use strict';

  /**
   * Invitation service.
   * @module api/InvitationApi
   * @version 1.0
   */

  /**
   * Constructs a new InvitationApi. 
   * @alias module:api/InvitationApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the create operation.
     * @callback module:api/InvitationApi~createCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InvitationDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This method create a invitation for user
     * xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
     * @param {module:model/InvitationDTO} body Data of the invitation
     * @param {module:api/InvitationApi~createCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InvitationDTO}
     */
    this.create = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling create");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key', 'token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InvitationDTO;

      return this.apiClient.callApi(
        '/invitation', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
