/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MomitApi) {
      root.MomitApi = {};
    }
    root.MomitApi.SystemtypeApi = factory(root.MomitApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Systemtype service.
   * @module api/SystemtypeApi
   * @version 1.0
   */

  /**
   * Constructs a new SystemtypeApi. 
   * @alias module:api/SystemtypeApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getByDeviceTypeAndSystemTypeName operation.
     * @callback module:api/SystemtypeApi~getByDeviceTypeAndSystemTypeNameCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This method returns the list of systemtypes availables in the API
     * If the query param deviceTypeId is null all systemTypes will be returned 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.deviceTypeId Id of the device type
     * @param {String} opts.systemTypeName Id of the systemtype
     * @param {module:api/SystemtypeApi~getByDeviceTypeAndSystemTypeNameCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getByDeviceTypeAndSystemTypeName = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'deviceTypeId': opts['deviceTypeId'],
        'systemTypeName': opts['systemTypeName']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key', 'token'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/systemType', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
