/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MomitApi);
  }
}(this, function(expect, MomitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MomitApi.CalendarPeriodDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CalendarPeriodDTO', function() {
    it('should create an instance of CalendarPeriodDTO', function() {
      // uncomment below and update the code to test CalendarPeriodDTO
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be.a(MomitApi.CalendarPeriodDTO);
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property weekDayActive (base name: "weekDayActive")', function() {
      // uncomment below and update the code to test the property weekDayActive
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property setPoint (base name: "setPoint")', function() {
      // uncomment below and update the code to test the property setPoint
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property startHour (base name: "startHour")', function() {
      // uncomment below and update the code to test the property startHour
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property startMinute (base name: "startMinute")', function() {
      // uncomment below and update the code to test the property startMinute
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property stopHour (base name: "stopHour")', function() {
      // uncomment below and update the code to test the property stopHour
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property stopMinute (base name: "stopMinute")', function() {
      // uncomment below and update the code to test the property stopMinute
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property onMonday (base name: "onMonday")', function() {
      // uncomment below and update the code to test the property onMonday
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property onTuesday (base name: "onTuesday")', function() {
      // uncomment below and update the code to test the property onTuesday
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property onWednesday (base name: "onWednesday")', function() {
      // uncomment below and update the code to test the property onWednesday
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property onThursday (base name: "onThursday")', function() {
      // uncomment below and update the code to test the property onThursday
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property onFriday (base name: "onFriday")', function() {
      // uncomment below and update the code to test the property onFriday
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property onSaturday (base name: "onSaturday")', function() {
      // uncomment below and update the code to test the property onSaturday
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property onSunday (base name: "onSunday")', function() {
      // uncomment below and update the code to test the property onSunday
      //var instane = new MomitApi.CalendarPeriodDTO();
      //expect(instance).to.be();
    });

  });

}));
