/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MomitApi);
  }
}(this, function(expect, MomitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MomitApi.MeasureDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MeasureDTO', function() {
    it('should create an instance of MeasureDTO', function() {
      // uncomment below and update the code to test MeasureDTO
      //var instane = new MomitApi.MeasureDTO();
      //expect(instance).to.be.a(MomitApi.MeasureDTO);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new MomitApi.MeasureDTO();
      //expect(instance).to.be();
    });

    it('should have the property numberFormat (base name: "numberFormat")', function() {
      // uncomment below and update the code to test the property numberFormat
      //var instane = new MomitApi.MeasureDTO();
      //expect(instance).to.be();
    });

    it('should have the property dateFormat (base name: "dateFormat")', function() {
      // uncomment below and update the code to test the property dateFormat
      //var instane = new MomitApi.MeasureDTO();
      //expect(instance).to.be();
    });

    it('should have the property hourFormat (base name: "hourFormat")', function() {
      // uncomment below and update the code to test the property hourFormat
      //var instane = new MomitApi.MeasureDTO();
      //expect(instance).to.be();
    });

    it('should have the property firstDayWeek (base name: "firstDayWeek")', function() {
      // uncomment below and update the code to test the property firstDayWeek
      //var instane = new MomitApi.MeasureDTO();
      //expect(instance).to.be();
    });

    it('should have the property distanceMeasure (base name: "distanceMeasure")', function() {
      // uncomment below and update the code to test the property distanceMeasure
      //var instane = new MomitApi.MeasureDTO();
      //expect(instance).to.be();
    });

    it('should have the property temperatureMeasure (base name: "temperatureMeasure")', function() {
      // uncomment below and update the code to test the property temperatureMeasure
      //var instane = new MomitApi.MeasureDTO();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new MomitApi.MeasureDTO();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instane = new MomitApi.MeasureDTO();
      //expect(instance).to.be();
    });

  });

}));
