/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MomitApi);
  }
}(this, function(expect, MomitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MomitApi.MyBudgetRatePeriodDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MyBudgetRatePeriodDTO', function() {
    it('should create an instance of MyBudgetRatePeriodDTO', function() {
      // uncomment below and update the code to test MyBudgetRatePeriodDTO
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be.a(MomitApi.MyBudgetRatePeriodDTO);
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property ratePeriodId (base name: "ratePeriodId")', function() {
      // uncomment below and update the code to test the property ratePeriodId
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property rate (base name: "rate")', function() {
      // uncomment below and update the code to test the property rate
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property cost (base name: "cost")', function() {
      // uncomment below and update the code to test the property cost
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property startHour (base name: "startHour")', function() {
      // uncomment below and update the code to test the property startHour
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property startMin (base name: "startMin")', function() {
      // uncomment below and update the code to test the property startMin
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property stopHour (base name: "stopHour")', function() {
      // uncomment below and update the code to test the property stopHour
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property stopMin (base name: "stopMin")', function() {
      // uncomment below and update the code to test the property stopMin
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property mon (base name: "mon")', function() {
      // uncomment below and update the code to test the property mon
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property tue (base name: "tue")', function() {
      // uncomment below and update the code to test the property tue
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property wed (base name: "wed")', function() {
      // uncomment below and update the code to test the property wed
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property thu (base name: "thu")', function() {
      // uncomment below and update the code to test the property thu
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property fri (base name: "fri")', function() {
      // uncomment below and update the code to test the property fri
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property sat (base name: "sat")', function() {
      // uncomment below and update the code to test the property sat
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property sun (base name: "sun")', function() {
      // uncomment below and update the code to test the property sun
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property invoiceType (base name: "invoiceType")', function() {
      // uncomment below and update the code to test the property invoiceType
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

    it('should have the property invoiceDay (base name: "invoiceDay")', function() {
      // uncomment below and update the code to test the property invoiceDay
      //var instane = new MomitApi.MyBudgetRatePeriodDTO();
      //expect(instance).to.be();
    });

  });

}));
