/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MomitApi);
  }
}(this, function(expect, MomitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MomitApi.StatsDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StatsDTO', function() {
    it('should create an instance of StatsDTO', function() {
      // uncomment below and update the code to test StatsDTO
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be.a(MomitApi.StatsDTO);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property year (base name: "year")', function() {
      // uncomment below and update the code to test the property year
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property month (base name: "month")', function() {
      // uncomment below and update the code to test the property month
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property day (base name: "day")', function() {
      // uncomment below and update the code to test the property day
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property isoWeek (base name: "isoWeek")', function() {
      // uncomment below and update the code to test the property isoWeek
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property isoDayWeek (base name: "isoDayWeek")', function() {
      // uncomment below and update the code to test the property isoDayWeek
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property hour (base name: "hour")', function() {
      // uncomment below and update the code to test the property hour
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property min (base name: "min")', function() {
      // uncomment below and update the code to test the property min
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property deviceId (base name: "deviceId")', function() {
      // uncomment below and update the code to test the property deviceId
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property timeZone (base name: "timeZone")', function() {
      // uncomment below and update the code to test the property timeZone
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property timeStamp (base name: "timeStamp")', function() {
      // uncomment below and update the code to test the property timeStamp
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property temperatureIn (base name: "temperatureIn")', function() {
      // uncomment below and update the code to test the property temperatureIn
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property temperatureOut (base name: "temperatureOut")', function() {
      // uncomment below and update the code to test the property temperatureOut
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property humidityIn (base name: "humidityIn")', function() {
      // uncomment below and update the code to test the property humidityIn
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property humidityOut (base name: "humidityOut")', function() {
      // uncomment below and update the code to test the property humidityOut
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property releAuxE (base name: "releAuxE")', function() {
      // uncomment below and update the code to test the property releAuxE
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property releOB (base name: "releOB")', function() {
      // uncomment below and update the code to test the property releOB
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property releGGL (base name: "releGGL")', function() {
      // uncomment below and update the code to test the property releGGL
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property releY2 (base name: "releY2")', function() {
      // uncomment below and update the code to test the property releY2
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property releYY1 (base name: "releYY1")', function() {
      // uncomment below and update the code to test the property releYY1
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property releW2 (base name: "releW2")', function() {
      // uncomment below and update the code to test the property releW2
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property releWW1 (base name: "releWW1")', function() {
      // uncomment below and update the code to test the property releWW1
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instane = new MomitApi.StatsDTO();
      //expect(instance).to.be();
    });

  });

}));
