/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MomitApi);
  }
}(this, function(expect, MomitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MomitApi.WeatherDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WeatherDTO', function() {
    it('should create an instance of WeatherDTO', function() {
      // uncomment below and update the code to test WeatherDTO
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be.a(MomitApi.WeatherDTO);
    });

    it('should have the property weatherTime (base name: "weatherTime")', function() {
      // uncomment below and update the code to test the property weatherTime
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

    it('should have the property serverTime (base name: "serverTime")', function() {
      // uncomment below and update the code to test the property serverTime
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

    it('should have the property icon (base name: "icon")', function() {
      // uncomment below and update the code to test the property icon
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

    it('should have the property temperature (base name: "temperature")', function() {
      // uncomment below and update the code to test the property temperature
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

    it('should have the property apparentTemp (base name: "apparentTemp")', function() {
      // uncomment below and update the code to test the property apparentTemp
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

    it('should have the property windSpeed (base name: "windSpeed")', function() {
      // uncomment below and update the code to test the property windSpeed
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

    it('should have the property humidity (base name: "humidity")', function() {
      // uncomment below and update the code to test the property humidity
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

    it('should have the property windBearing (base name: "windBearing")', function() {
      // uncomment below and update the code to test the property windBearing
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

    it('should have the property cloudCover (base name: "cloudCover")', function() {
      // uncomment below and update the code to test the property cloudCover
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

    it('should have the property pressure (base name: "pressure")', function() {
      // uncomment below and update the code to test the property pressure
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

    it('should have the property precipProb (base name: "precipProb")', function() {
      // uncomment below and update the code to test the property precipProb
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instane = new MomitApi.WeatherDTO();
      //expect(instance).to.be();
    });

  });

}));
