/**
 * Momit API
 * momit API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MomitApi);
  }
}(this, function(expect, MomitApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MomitApi.MybudgetApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MybudgetApi', function() {
    describe('addHvacPower', function() {
      it('should call addHvacPower successfully', function(done) {
        //uncomment below and update the code to test addHvacPower
        //instance.addHvacPower(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addRate', function() {
      it('should call addRate successfully', function(done) {
        //uncomment below and update the code to test addRate
        //instance.addRate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addRate_0', function() {
      it('should call addRate_0 successfully', function(done) {
        //uncomment below and update the code to test addRate_0
        //instance.addRate_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteHvacPower', function() {
      it('should call deleteHvacPower successfully', function(done) {
        //uncomment below and update the code to test deleteHvacPower
        //instance.deleteHvacPower(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRate', function() {
      it('should call deleteRate successfully', function(done) {
        //uncomment below and update the code to test deleteRate
        //instance.deleteRate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRatePeriod', function() {
      it('should call deleteRatePeriod successfully', function(done) {
        //uncomment below and update the code to test deleteRatePeriod
        //instance.deleteRatePeriod(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDevice', function() {
      it('should call getDevice successfully', function(done) {
        //uncomment below and update the code to test getDevice
        //instance.getDevice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnergyUnitById', function() {
      it('should call getEnergyUnitById successfully', function(done) {
        //uncomment below and update the code to test getEnergyUnitById
        //instance.getEnergyUnitById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnergyUnitById_0', function() {
      it('should call getEnergyUnitById_0 successfully', function(done) {
        //uncomment below and update the code to test getEnergyUnitById_0
        //instance.getEnergyUnitById_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getHvacPower', function() {
      it('should call getHvacPower successfully', function(done) {
        //uncomment below and update the code to test getHvacPower
        //instance.getHvacPower(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPrediction', function() {
      it('should call getPrediction successfully', function(done) {
        //uncomment below and update the code to test getPrediction
        //instance.getPrediction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRateById', function() {
      it('should call getRateById successfully', function(done) {
        //uncomment below and update the code to test getRateById
        //instance.getRateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRatePeriodById', function() {
      it('should call getRatePeriodById successfully', function(done) {
        //uncomment below and update the code to test getRatePeriodById
        //instance.getRatePeriodById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRatesByDevice', function() {
      it('should call getRatesByDevice successfully', function(done) {
        //uncomment below and update the code to test getRatesByDevice
        //instance.getRatesByDevice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRatesPeriodByRate', function() {
      it('should call getRatesPeriodByRate successfully', function(done) {
        //uncomment below and update the code to test getRatesPeriodByRate
        //instance.getRatesPeriodByRate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateGoalCost', function() {
      it('should call updateGoalCost successfully', function(done) {
        //uncomment below and update the code to test updateGoalCost
        //instance.updateGoalCost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateRate', function() {
      it('should call updateRate successfully', function(done) {
        //uncomment below and update the code to test updateRate
        //instance.updateRate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateRatePeriod', function() {
      it('should call updateRatePeriod successfully', function(done) {
        //uncomment below and update the code to test updateRatePeriod
        //instance.updateRatePeriod(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
